heat_template_version: 2015-04-30

parameters:
  ControlPlaneIp:
    default: ''
    type: string
  ExternalIp:
    default: ''
    type: string
  InternalApiIp:
    default: ''
    type: string
  StorageIp:
    default: ''
    type: string
  StorageMgmtIp:
    default: ''
    type: string
  TenantIp:
    default: ''
    type: string

outputs:
  net_ip_map:
    description: >
      A Hash containing a mapping of network names to assigned IPs
      for a specific machine.
    value:
      ctlplane: {get_param: ControlPlaneIp}
      external: {get_param: ExternalIp}
      internal_api: {get_param: InternalApiIp}
      storage: {get_param: StorageIp}
      storage_mgmt: {get_param: StorageMgmtIp}
      tenant: {get_param: TenantIp}
