heat_template_version: 2015-04-30

description: >
  Internodos network. Internodos traffic, Neutron l3router for floating IPs/SNAT, etc.

parameters:
  # the defaults here work for static IP assignment (IPAM) only
  InternodosNetCidr:
    default: '10.0.0.0/24'
    description: Cidr for the Internodos network.
    type: string
  InternodosNetValueSpecs:
    default: {'provider:physical_network': 'internodos', 'provider:network_type': 'flat'}
    description: Value specs for the Internodos network.
    type: string
  InternodosNetAdminStateUp:
    default: false
    description: This admin state of of the network.
    type: boolean
  InternodosNetEnableDHCP:
    default: false
    description: Whether to enable DHCP on the associated subnet.
    type: boolean
  InternodosNetShared:
    default: false
    description: Whether this network is shared across all tenants.
    type: boolean
  InternodosNetName:
    default: internodos
    description: The name of the Internodos network.
    type: string
  InternodosSubnetName:
    default: internodos_subnet 
    description: The name of the Internodos subnet in Neutron.
    type: string
  InternodosAllocationPools:
    default: [{'start': '10.0.0.4', 'end': '10.0.0.250'}]
    description: Ip allocation pool range for the Internodos network.
    type: json

resources:
  InternodosNetwork:
    type: OS::Neutron::Net
    properties:
      admin_state_up: {get_param: InternodosNetAdminStateUp}
      name: {get_param: InternodosNetName}
      shared: {get_param: InternodosNetShared}
      value_specs: {get_param: InternodosNetValueSpecs}

  InternodosSubnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: {get_param: InternodosNetCidr}
      enable_dhcp: {get_param: InternodosNetEnableDHCP}
      name: {get_param: InternodosSubnetName}
      network: {get_resource: InternodosNetwork}
      allocation_pools: {get_param: InternodosAllocationPools}

outputs:
  OS::stack_id:
    description: Neutron Internodos network
    value: {get_resource: InternodosNetwork}
