heat_template_version: 2015-04-30

description: >
  Internet network. Internet traffic, Neutron l3router for floating IPs/SNAT, etc.

parameters:
  # the defaults here work for static IP assignment (IPAM) only
  InternetNetCidr:
    default: '10.0.0.0/24'
    description: Cidr for the Internet network.
    type: string
  InternetNetValueSpecs:
    default: {'provider:physical_network': 'internet', 'provider:network_type': 'flat'}
    description: Value specs for the Internet network.
    type: string
  InternetNetAdminStateUp:
    default: false
    description: This admin state of of the network.
    type: boolean
  InternetNetEnableDHCP:
    default: false
    description: Whether to enable DHCP on the associated subnet.
    type: boolean
  InternetNetShared:
    default: false
    description: Whether this network is shared across all tenants.
    type: boolean
  InternetNetName:
    default: internet
    description: The name of the Internet network.
    type: string
  InternetSubnetName:
    default: internet_subnet
    description: The name of the Internet subnet in Neutron.
    type: string
  InternetAllocationPools:
    default: [{'start': '10.0.0.4', 'end': '10.0.0.250'}]
    description: Ip allocation pool range for the Internet network.
    type: json

resources:
  InternetNetwork:
    type: OS::Neutron::Net
    properties:
      admin_state_up: {get_param: InternetNetAdminStateUp}
      name: {get_param: InternetNetName}
      shared: {get_param: InternetNetShared}
      value_specs: {get_param: InternetNetValueSpecs}

  InternetSubnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: {get_param: InternetNetCidr}
      enable_dhcp: {get_param: InternetNetEnableDHCP}
      name: {get_param: InternetSubnetName}
      network: {get_resource: InternetNetwork}
      allocation_pools: {get_param: InternetAllocationPools}

outputs:
  OS::stack_id:
    description: Neutron Internet network
    value: {get_resource: InternetNetwork}
